---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  labels:
    managed-by: flux
    config.linkerd.io/admission-webhooks: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-smi
  labels:
    managed-by: flux
