apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkerd-smi
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
    - name: linkerd-control-plane
      namespace: flux-system
  chart:
    spec:
      chart: linkerd-smi
      sourceRef:
        kind: HelmRepository
        name: linkerd-smi
        namespace: flux-system
      interval: 12h
  targetNamespace: linkerd-smi
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
