apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: staging
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 150m
        memory: 192Mi
      default:
        cpu: 700m
        memory: 768Mi
      min:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "2"
        memory: 2Gi
