apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: staging
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 64Mi
      default:
        cpu: 700m
        memory: 768Mi
      min:
        cpu: 10m
        memory: 32Mi
      max:
        cpu: "2"
        memory: 2Gi
