language: en-US
early_access: false
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true
  path_instructions:
    - path: "**"
      instructions: |
        - CONTEXT: SRE DevOps repository — k3s on Hetzner Cloud, FluxCD GitOps, Terraform IaC
        - KISS principle: simple > complex in all decisions
        - Be strict on: security vulnerabilities, breaking changes, secret leaks, resource misconfigurations
        - Be fair on: established patterns, professional DevOps judgment, controlled environments
        - Keep reviews concise and actionable — focus on high-impact issues only
    - path: "**/*.tf"
      instructions: |
        - Terraform manages Hetzner k3s cluster via kube-hetzner module
        - State is remote in Cloudflare R2 (S3-compatible backend)
        - Sensitive variables come from TF_VAR_* environment variables, not .tfvars
        - Check: resource dependencies, lifecycle blocks, destroy provisioner safety
        - Check: null_resource provisioners have on_failure = continue and timeouts for destroy
        - Verify pinned versions for modules and providers
        - Kubernetes provider uses fileexists() guard for kubeconfig — don't remove this pattern
    - path: "flux/**/*.yaml"
      instructions: |
        - FluxCD GitOps manifests — Kustomizations, HelmReleases, secrets
        - Pattern: base/ + overlays/{develop,staging,production}/patches/
        - Check: dependsOn chains are correct (infrastructure → secrets → apps)
        - Check: HelmRelease versions are pinned (not semver ranges)
        - Check: SOPS-encrypted secrets have correct namespace and encrypted_regex
        - Check: NetworkPolicies allow traffic from traefik namespace (not ingress-nginx)
        - Check: ResourceQuota and LimitRange values are consistent across environments
        - Ingress uses traefik ingressClassName with cert-manager.io/cluster-issuer annotation
        - cert-manager uses DNS-01 challenge with Cloudflare (not HTTP-01)
    - path: "**/.pre-commit-config.yaml"
      instructions: |
        - Verify default_install_hook_types includes all used stages
        - Check terraform fmt uses -check flag to fail on unformatted files
        - Verify prepare-commit-msg hooks have pass_filenames: false
        - Ensure security scanning (checkov) does not use --soft-fail
    - path: "**/*.sh"
      instructions: |
        - Scripts must use set -e minimum; critical scripts use set -Eeuo pipefail
        - Check proper quoting of variables, especially file paths
        - Verify shift operations are guarded by argument count checks
        - Infrastructure scripts must fail fast with clear error messages
    - path: "**/.github/workflows/*.yml"
      instructions: |
        - Terraform CI/CD with manual approval gates for apply/destroy
        - Check: github.token (lowercase) not github.TOKEN
        - Check: cancel-in-progress is false for apply/destroy workflows
        - Check: user inputs are passed via env vars, not direct interpolation in shell
        - Check: approval steps have timeout-minutes set
        - Verify proper secret handling — no secrets in logs
    - path: "**/Makefile"
      instructions: |
        - Root Makefile delegates to sub-Makefiles via $(MAKE) -C
        - hcloud_cluster Makefile handles state cleanup for safe destroy
        - Check: destroy target removes flux/k8s resources from state before terraform destroy
        - Verify .PHONY declarations match actual targets
    - path: "**/CLAUDE.md"
      instructions: |
        - Repository guidelines for AI agents — learn and apply these principles
        - Reference these guidelines when reviewing other files
  path_filters:
    - "**/*.tf"
    - "**/*.tfvars"
    - "flux/**/*.yaml"
    - "**/*.sh"
    - "**/*.py"
    - "**/.pre-commit-config.yaml"
    - "**/CLAUDE.md"
    - "**/Makefile"
    - "**/.github/workflows/*.yml"
    - "!**/.terraform/**"
    - "!**/.terraform.lock.hcl"
    - "!**/node_modules/**"
    - "!**/*.log"
  tools:
    gitleaks:
      enabled: true
    semgrep:
      enabled: true
    checkov:
      enabled: true
    hadolint:
      enabled: true
    yamllint:
      enabled: true
    actionlint:
      enabled: true

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CLAUDE.md"
  learnings:
    scope: "local"
  issues:
    scope: "local"
  pull_requests:
    scope: "local"

chat:
  auto_reply: false
tone_instructions: "KISS principle: simple > complex. Assertive on security, secret leaks, breaking changes. Focus on infrastructure safety and production reliability. Skip theoretical concerns for controlled environments."
