apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      interval: 12h
  targetNamespace: flagger-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    crd:
      create: true
    meshProvider: linkerd
    metricsServer: http://kube-prometheus-stack-prometheus.observability:9090
    linkerdAuthPolicy:
      create: true
