---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: backend
  namespace: develop
spec:
  imageRepositoryRef:
    name: backend
    namespace: flux-system
  policy:
    semver:
      range: '>=0.0.0-rc'
  filterTags:
    pattern: '^.*-rc-.*$'
