---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: backend
  namespace: production
spec:
  imageRepositoryRef:
    name: backend
    namespace: flux-system
  filterTags:
    pattern: '^production-[a-f0-9]+-(?P<ts>[0-9]+)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
