---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: backend
  namespace: production
spec:
  imageRepositoryRef:
    name: backend
    namespace: flux-system
  filterTags:
    pattern: '^v\d+\.\d+\.\d+$'
  policy:
    semver:
      range: '>=0.0.1'
