apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
namePrefix: ""
labels:
  - pairs:
      environment: production
    includeSelectors: true
    includeTemplates: true
resources:
  - ../base
  - image-policy.yaml
  - image-automation.yaml
  - hpa.yaml
  - pdb.yaml
images:
  - name: backend
    newName: ${image_registry}/backend
    newTag: production-v0.0.0-7890945-1791154832 # {"$imagepolicy": "production:backend:tag"}
