apiVersion: v1
kind: Secret
metadata:
    name: uptrace-secrets
    namespace: develop
type: Opaque
stringData:
    dsn: ENC[AES256_GCM,data:dOeqIls70LZo33Ff5XVXVuS1rDRLZYe8p9FdvxSkzsVBMSkeLHNPflc97X0Ph0AVDSG1gatZZog=,iv:FyBxYYNoRfLgmYrxHPG2dcWWNgyX1eGwN8hLQ8eGet8=,tag:lHMpLnaEeKShxhwtSAGu+w==,type:str]
sops:
    age:
        - recipient: age1730wxdzhzpwjmf04rdf9tdz5zndr7xjq2mqk5ydkme5s27vaha7s2xnjxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScHZ0dE8raGpERVEzUTVW
            VC9LdHdKaFlyQXBmbkREMHZNQzNxY1JRdlQwCkZnYkVHVVB0SWl3d1JVUXZCcHYv
            N0U0VFZTRVgzSUJpaVdVK3VNVlpYeEUKLS0tIGpEbjJ4dmtyZjVLK29oVFZrVUd5
            a1VyanlsYWlqK0QrNktxTGt2TEREMzQK/izJHQ0Tyg59A3//ZGdtD+dHV5LsRC59
            Ny/oneKLMW1UhLBH6q7lV//ADC9KzOAuJ2ebgMxT1o2e5HUU4E0wMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T08:29:13Z"
    mac: ENC[AES256_GCM,data:VXOYf7GiSgcFSata2JxC7n14SW65E6jJW+WHW/ZO4HzkIWhfsgNoTHCo0b97IvCWjJP952RxPJJC2TwQX344v4oS2OBFxB8bteIliUZexw7opZsE4xWbQudkBTFkmAVTOWDbflbCZDebLGmxMWU+2GmNy0Ufl9e1BjgNWA+vYRE=,iv:9EKR4ww+nKzt7I/TCQDgCxfXrsqyBt5lMfMtY7wtf7Q=,tag:1vTrsbWJALvn953KtmwhqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
