---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: backend
  namespace: staging
spec:
  imageRepositoryRef:
    name: backend
    namespace: flux-system
  policy:
    semver:
      range: '>=0.0.0'
  filterTags:
    pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
