---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: backend
  namespace: staging
spec:
  imageRepositoryRef:
    name: backend
    namespace: flux-system
  filterTags:
    pattern: '^v\d+\.\d+\.\d+-[a-f0-9]+$'
  policy:
    semver:
      range: '>=0.0.0'
