apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:t3amxDMRMbXeN8H6whRdDFGa5ODaZkeOeoZCnpd3e4BKbkiuDFXlLw==,iv:7L/RaVacJRdGEXGqnnWVz/JPtA63ihZjF9WYoxmRzOg=,tag:f+tTtBzk+8pLZOsaakV0Qw==,type:str]
sops:
    age:
        - recipient: age1730wxdzhzpwjmf04rdf9tdz5zndr7xjq2mqk5ydkme5s27vaha7s2xnjxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTERnWXMrbnM0dmUzZE02
            UTEwY2U2bUtHYUpmam9xSjJ6SmtKbWh3bFJjCnU1cUFFaXhsN2ZhVHFaTURtVDNj
            dEs5dU91TDhlZkJ5SkxxdjVMRENlc0kKLS0tIHFFNHozL1k0WDlFVGY0OHZkaTY2
            Zjh3TDFlY3FmbUh2bGNFZkx6dkFva28Kqg2hJM8wXZiazzD+mxt3hWgihstsHp6m
            txkr7hHYjvPxlYfUNqwagpZETQzg2P5uXHmZMLbMQg1a528r8Wwl9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T19:36:30Z"
    mac: ENC[AES256_GCM,data:pMGygbtDeJ2XXPXYSHi8tbSD299eeLnU6LBkP8PRF7Hc7FPuzkpaFlFd17J+epuyCLJrra6khIfHjtQ/j6OEbXy3khJVDqHEBskoNgqp0faW/unarb8KrN58UEMP9bI0JpJ1ugV77sogiypmtKKsX+y0b2LJuteFCfB/BMsEeMk=,iv:eYn9SUUFz+g8gcgTfhoE0FKqQ/3RXVXQY9EaGL+TTDQ=,tag:kxVgOMIf1utugkDbbbJdqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
