apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-origin-ca-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:3VMpGsbgdWChXCZ1/S4NEhLWKag7np71rSTJYef4kKwkyyq25War0MbV7RUwlrSlSNjlaP0=,iv:M0i/TG8Z5YCJ3s1pfZ1mcpJuYdDmEOPYUFJw8M6HIKU=,tag:Ia1XxJL3FAVYR0j7/ptifg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRUZLUmtrUVFjY0hkeTVR
            VEx4cUk2em1hL3VhUENaNUpsODZXNzJDQkVZCnhKOUhSVjJOOG1uS1Jpa2dhTWky
            b2pGNUptd2o2NlVTTUFrS3BuaWYwUmMKLS0tIEgya3hpRzZqSWFQZStmd2xENnRj
            T0l0bDhlWkZzL1NyTjJNTkxCWXA1S28K4UICFMUk5DsmKnFQ/qC/IlSclGSK4bqr
            1ke8iUX/T8hOzzuic/T4IuTED6QIVT9VnT2lMNhYyUKmsI7OGayzYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykac8h2lhgvppswhutsmsqu6cw0ht30wfjw9k7ghl6p8t5542y8s43zthp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T22:38:47Z"
    mac: ENC[AES256_GCM,data:lkXzVLYBBUMTYaAQ9aCQTI9s3/mkOj7reb+2f31V8gp0MgpZ2GbZHQFDw8kKZeiCL1iySdKujrUgygKyJ6DA1WIJUKxtL7EHfAoJ57t3vC+/X66FhRBkoq/WZP64+W0uDBx21Bf1zOD3Etbwv5iUZ7UzYirHeEn2YhrxPoq38u8=,iv:TNRj8tjSe5tElL9f1BJl7z81ng8TYudmgOFg9S9ywnI=,tag:/usNq8iD88KVNYDLK6+hiQ==,type:str]
    version: 3.13.3
