apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
    namespace: staging
type: Opaque
stringData:
    uptrace-dsn: ENC[AES256_GCM,data:Eav+6P1iv8tkCl9fSQ7n0junb8nCURskGlDWBfRJS/4seWm7J0I0RXy1+Df+nkiV8vLh28YQeqw=,iv:pfKTxGJmwLSTRZ1mst45GTAhMaiPlwLNf/xoo8ZlZSo=,tag:bWuNfRMeeX+3N8OpkKdwwg==,type:str]
    uptrace-headers: ENC[AES256_GCM,data:Y50eRD46IFUNPKWfcUoPsi1AkY5SBuSLcMcZF2T37o1l8O75TRWq+tXR2WOoOIr5lRPJ9GAvT3DuAmDoBNFn+aE1ne8=,iv:eYyy2gp6waIVWmYwI0o82xc3xbtLtVsBFd/ixPlp5tQ=,tag:Hnoy7NuXuhgm/8Yi00utgQ==,type:str]
    jwt-secret: ENC[AES256_GCM,data:PnUun+Cd5EUfB3pgym2Fc5q4djGphyvX02V7PqOJ6Uwl9B1w+Xnbm0UAQk0=,iv:YPeLyCNQETpdl/OhwhpCL6kw9A3noCVfE7NzdjmsYN8=,tag:5Xdpa/z3b0RIJrzhzUXv9w==,type:str]
sops:
    age:
        - recipient: age1730wxdzhzpwjmf04rdf9tdz5zndr7xjq2mqk5ydkme5s27vaha7s2xnjxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL3lHVU5PbkgxWjJzVGVt
            UU9NeWdZNjExR1pjQzBGVHY2emYyckI5UWdNCi9XTVNTQ1lvZlhjaHBjeTVxSkJB
            K0h0aWtUb0tsTzRVRjhCaGszTEZjSkUKLS0tIGhrMDRVTFZXdGNia3ZldEtZMHor
            ZGh1ZU94NkR4RXVHYmYxMUxXbGtrVVUKYRAUN4NltkWjSd0h0cj63hhci7KiO61G
            CHLGuYokmJaSvbzPsPiVQedFBtRvvYVN2fyfl0JHUMhA/vKL60dikg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T17:58:24Z"
    mac: ENC[AES256_GCM,data:AxRA+vAizXnnj8u5xRhoXRS0S/mJvE9Lm7w7CezUTj5Vm8TRIu9HIthqaIzT3vIWKOWnhSlogZxJbwLlwSKzs679CeYnFSrMI1ZRtbyCH9JO7syn5AIwn/pNnC5HgKrogKY8RQVWVqBewNVGBMwtYXpQG1ONZR2AM11Oqb9wbdM=,iv:iK6zSSYl0SPFnIsYpGxMqay3USLsqH+gyJxd/RLG/4U=,tag:UT053RzbsnYrBEGc8R76gw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
