apiVersion: v1
kind: Secret
metadata:
    name: uptrace-secrets
    namespace: staging
type: Opaque
stringData:
    dsn: ENC[AES256_GCM,data:o9gdslSZrtOZEViKYC5bLmGngyMvT658i6lbBkD8gfjU2JFLBXjzUbP3vM6rr2vlNyntPhuRL+4=,iv:RyLvEhoV1W9reX7YTLxBAp8/2UUyH8RqZ9PgeDyWZo4=,tag:hBasZ0ctXQ6LOzIbT8UBzA==,type:str]
sops:
    age:
        - recipient: age1730wxdzhzpwjmf04rdf9tdz5zndr7xjq2mqk5ydkme5s27vaha7s2xnjxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZ1NWL21kRmNWbmxzWkJS
            c1pVeXp1RUFML1V6L3ljUWhiSVRoMStWRlM0CmFGQnlpekxvOTd3MytXeFBTNWJE
            ckdRK3NxVnNMRm1wYXlvMWVjVURualUKLS0tIG1zdXNRMW11VWlTLzhNVUc1SXRM
            NTlJenJLc3Z5SlA3LzNCMVU4Z0tGMVkKIABLQCdvNKrMXnO2KugG/W/3YWu6YOIu
            2SzqfkA5Dyn+Y9jMr2wZYjySXoVyZJ5z26vitYMSa1gwZ0fSCvl9ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T08:29:14Z"
    mac: ENC[AES256_GCM,data:soZZ6EN4f6lKfK2S7lPbU5Fa6YNeE1tIuWIpBPcjGETRUvF4lFvmtNstMkMlGuGmaZwf44QxWBkWPk2gPgHfZOPUat3Cvb9z9x1i2N+KWw3yZPWuO0HdDKAOjykeAhphIEtMgodVwC4qXNn1R8n12Es/9F7x2iXyd1Q9Q+wr6sQ=,iv:Fhh6UpwUfggEIzEnRk27ymxMRJkR4Fh9q+TT7+PRR2o=,tag:3QehQ2KxE8G/QlWetY9Wuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
