apiVersion: v1
kind: Secret
metadata:
    name: uptrace-secrets
    namespace: staging
type: Opaque
stringData:
    dsn: ENC[AES256_GCM,data:aI9+il/LoCKNN72lNE2hoXSJfcxg+EznQYLjpb2eoH5KZVpo4JFXE0NQEPG6tw==,iv:A6qT6dQ8x2E2dm0lK7/sDk8ea15JmZIqDagtWqAFV+Q=,tag:vDCMVjnp/PlPs/jW7tx52w==,type:str]
sops:
    age:
        - recipient: age1730wxdzhzpwjmf04rdf9tdz5zndr7xjq2mqk5ydkme5s27vaha7s2xnjxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTWlSSGpRK0N5MEJBTkVm
            byttOWlRZUxsSFpma0c5WWJPSjVSclpCRVVFCis2Zjg1N1hnTm1JSGFsMWZubzVu
            Q2hLVXNZTU44U3dkU3Z5dlBSYlo2YWsKLS0tIHdnTFIvYmtoT0xQU2psTURZMHNp
            OFExV0pEZ0FyQUh2WWR2TmY4T0M0UEkKgU7Brrhf7H67yBK3Pivdorh7JnkoA3BT
            0kFVTjE0aEFECkdqtc8nNTB2vuJtwP+NudHsPq3xVl/TWOvEYkSblg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T09:55:12Z"
    mac: ENC[AES256_GCM,data:30Q/6zScUOuoKlD/LFwgoEA3TiPOZK2wNAC0yTswSFdBUKNKamvZdd2WZ41VcZI69rqQ1G5scBiW1DHQK2+DlBcq5HQ6cH6LXsDCZytK2rmndnxlqVQpD5/GIeFB+WWvoniB0BSdex3M0MjH0F+QlislL8g61ZK4Uf3K9dzxGCk=,iv:EnZ/ZRyPrz61A3C/mE0wvy9XTzmCYButzc+q+x2ktzQ=,tag:4epPRMt+P8qI/A9OPyrvSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
