apiVersion: v1
kind: Secret
metadata:
    name: uptrace-secrets
    namespace: staging
type: Opaque
stringData:
    dsn: ENC[AES256_GCM,data:dkVUfohskkRZsuToAd2CNlEmeWUggJR5hO1OpQqt5rRhHnx+lfScN4VeU8leWOhXB+q7Z7ovLHs=,iv:XJ2Suz4ElnCx+kFpabDFA2A4kKUz0n3xW2pHgKAv0ME=,tag:FOceDTPrG0E6+Ys+MVlPuQ==,type:str]
    headers: ENC[AES256_GCM,data:LRVfUjd1HcEb4P62ebBHxSEi+ILq31OlczhmBtGeSRQeF3VIdDaJELh0XrtmmtCI2mQR/DM5qZTyQ1eMPrRmKpJSsf8=,iv:Cg+Hv0NvlcEPRpaIgyg5O40C82s4U5YY0mW9XAtyFrI=,tag:dCFXHrbdhAZuSvvjnM4JDA==,type:str]
sops:
    age:
        - recipient: age1730wxdzhzpwjmf04rdf9tdz5zndr7xjq2mqk5ydkme5s27vaha7s2xnjxl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRDRoalpZaXRFVHVuN1ZI
            TnA1S09NMTI5WWhKZ1Q1cnQ3bnRLK3VHUUhNCjZCNkt2andmd2x2blZZZThvcFVU
            RDk4K1g4b0JwWlloWlV3Z3BiTGNjVGMKLS0tIHk0L3FDR0hDMGcvVm5MSFNsN3l6
            T2Z6K2E3eU1TdjF2QUltNHIyNTJhMEEKRQZY7MUjzkmRgG1gGBOcI0TEUI4pIyc+
            isZZljOOcnRxdoOmb6s+QbVg2S2qDZux2HwH7R3eH0mWoK6bB/2ZLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T16:55:32Z"
    mac: ENC[AES256_GCM,data:gQfKE6zTBooUVrBqqpIBGdBr1piIpWgEB/E3C62serZWJa81eCG8JCXNLZR5PRnhwYNmUEzJ+ub4oqIK8V6ZepedjT6MOIVRaB7iHuAteoNqYgS2/7gIaNgmBWxYnt2bPk5tpEEPucsCQplrjxywmySJzp8TanbmGfFuL1yI39E=,iv:pOg/tjUT95MUYI/LByr4grqqGRRPcXCxhb69qt9QujU=,tag:sRNkE2VTnajQAz7cjlRBHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
