---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: ">=1.15.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  targetNamespace: cert-manager
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token
    extraArgs:
      - --cloudflare-proxied
    domainFilters:
      - safeops.work
    policy: sync
    sources:
      - ingress
    txtOwnerId: sre-cluster
