apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-heartbeat
    namespace: observability
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:eA2DTDjZVMUR7o+faYjttSq2Jihvvw0Cu1r1oSoMXHurGscvC1URU2ZG20zTOhlr91Bj3B9XpUo=,iv:R5ZNscHXG60hyD2Mucw3gqxZh3fyT/VPMlu5TUHDNQQ=,tag:GzMNbsULacm5TfGP/EIhAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaDcza0RWUllhSWs4MEty
            Z05kb1JycGhwbjJ1L3RveEtKS25XcER6b1c4ClpRSWlkdk5WMWt2aVRTcW9wTWpC
            YVZmNm9DeFZyVW1UU3dPcVdYa0NVdEUKLS0tIEpONzVBM3NOQVAxMElYUERheFBw
            cjBxWFU4M3lST0NkMUZWbnNoT0FhUmcKnXsSczvwcfHMj0zoEu75jmu0C7lZdzYL
            lYZ5/JA/wldeFTXVsiAvM2YEgyMLq5CcKos8RGIENSJAoKwX300YhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ykac8h2lhgvppswhutsmsqu6cw0ht30wfjw9k7ghl6p8t5542y8s43zthp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T20:55:33Z"
    mac: ENC[AES256_GCM,data:zDZ5cBuxACpMJ7ZQB925cdnreMu/lCKJTNi5OevL5LkCpBteBrIwkhI4bjWREpdFeWAcXA8NcDx+k+pV8H8hz6qWt6U6T6Q1WqFi5JSpavYAjV9BJjtAhIwiah/q2Gy+eN7/CNGcvLxWZXedypGOPhxQ0Yqh0kopXqqRvQe4iZI=,iv:f1Emk7DJuajxhWzR98cNj3Q3/DGuKsYySeRF19gbXpg=,tag:UbEC1hFEYPpDUF46iBnv+Q==,type:str]
    version: 3.13.3
